---
post_url: https://discourse.onlinedegree.iitm.ac.in/t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/500
---
sir I am noticing a pattern, that when I am running the datagen first. And then using the evaluate.py, then I am getting the A2 right.  
But running the evaluation.py for the 2nd time cause the A2 to fail…  
Probabbly Because the file in the data folder gets upated should I worry for that…