---
post_url: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/216
---
[@Jivraj](/u/jivraj) sir I get this error  
but my app.py is able to get the server running on localhost and not on 0.0.0.  

[![image](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/e/d/ed519f25f712a007f48e1e2f3cf5cf7f946271cb.png)

image1014Ã—190 18.2 KB](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/e/d/ed519f25f712a007f48e1e2f3cf5cf7f946271cb.png "image")

  
could you please help ?